version: '3'
services:
  calculate-credit-score:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: credit-score
    container_name: calculate-credit-score
    restart: always
    volumes:
      - .:/project
    command: |
      bash -c "
        sleep 10
        python3 ./calculate_credit_score/docker_run/run_frequently.py

      "
    depends_on:
      - neo4j-klg
    env_file:
      - ./.env
    environment:
      - MONGO_HOST
      - MONGO_PORT
      - NEO4J_HOST=neo4j_services_db-klg
      - NEO4J_BOTH_PORT=7687

  data-aggreagation:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: credit-score
    container_name: data-aggreagation
    restart: always
    volumes:
      - .:/project
    command: |
      bash -c "
        sleep 10
        python3 ./data_aggregation/docker_run/run_stream.py
      "
    depends_on:
      - neo4j-klg
    env_file:
      - ./.env
    environment:
      - MONGO_HOST
      - MONGO_PORT
      - NEO4J_HOST=neo4j_services_db-klg
      - NEO4J_BOTH_PORT=7687

  credit-score-rest-api-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: credit-score
    container_name: credit-score-rest-api-server
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/project
    command: |
      bash -c "
        sleep 10
        python3 ./rest_api_server/main.py
      "
    depends_on:
      - neo4j-klg
    env_file:
      - ./.env
    environment:
      - HOST
      - NEO4J_HOST=neo4j_services_db-klg
      - NEO4J_BOTH_PORT=7687

  neo4j-klg:
    image: neo4j:4.0.3
    hostname: neo4j_services_db
    container_name: neo4j_services_db-klg
    restart: always
    ports:
      - ${NEO4J_HTTP_PORT}:7474
      - ${NEO4J_HTTPS_PORT}:7473
      - ${NEO4J_BOTH_PORT}:7687
    volumes:
      - ./data/neo4j/plugins:/plugins
      - ./data/neo4j/data:/data
    env_file:
      - ./.env
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_http_timeout_connect=60000
      - NEO4J_apoc_http_timeout_read=120000
      - NEO4J_apoc_jobs_pool_num__threads=4
      - NEO4J_apoc_jobs_schedule_num__threads=4
      - NEO4J_apoc_spatial_geocode_provider=osm
      - NEO4J_apoc_spatial_geocode_osm_throttle=5000